---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: graytshirt/alpine-fetcher
  environment:
    MINIO_ACCESS_KEY:
      from_secret: minio_access_key
    MINIO_SECRET_KEY:
      from_secret: minio_secret_key
  commands:
  - export MC_HOST_minio="https://$MINIO_ACCESS_KEY:$MINIO_SECRET_KEY@titan01.iag.d3fy.net:9000"
  - make download
- name: build-pkgs
  image: graytshirt/alpine-builder
  environment:
    APK_KEY:
      from_secret: apk_key
    APK_KEY_PUB:
      from_secret: apk_key_pub
  commands:
  - make pkgs
- name: upload-pkgs
  image: graytshirt/alpine-fetcher
  environment:
    MINIO_ACCESS_KEY:
      from_secret: minio_access_key
    MINIO_SECRET_KEY:
      from_secret: minio_secret_key
    APK_KEY_PUB:
      from_secret: apk_key_pub
  commands:
  - export MC_HOST_minio="https://$MINIO_ACCESS_KEY:$MINIO_SECRET_KEY@titan01.iag.d3fy.net:9000"
  - make upload
- name: build-ami
  image: graytshirt/packer
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    AWS_DEFAULT_REGION: us-east-2
  commands:
  - make ami
---
kind: signature
hmac: 086c652c14806203955bd48a2173cb8ec87b6efef3b61f6b6a41ca20f662fb03

...
